name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          CACHE_VERSION: v1
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-dependencies-${{ env.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-dependencies-

      - name: Install dependencies
        run: yarn

      - name: Check formatting style, lint code and check types
        run: |
          yarn concurrently \
            'yarn style:check .' \
            'yarn lint .' \
            'yarn types:check'

      - name: Run tests
        run: yarn test
