name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  CACHE_VERSION: v1

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ env.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-dependencies-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check formatting style, lint code and check types
        run: yarn concurrently 'yarn types:check' 'yarn lint . --max-warnings=0' 'yarn style:check .'

      - name: Run tests
        run: yarn test:ci
