name: Release

on:
  push:
    branches: [main]

jobs:
  github-release:
    runs-on: ubuntu-latest
    environment: GitHub Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          CACHE_NAME: yarn-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Save necessary data to env
        run: |
          RELEASE_VERSION=$(node ./dev/release/getVersion.js)

          git fetch --tags
          EXISTING_RELEASE_VERSION=$(git tag -l v$RELEASE_VERSION)

          echo 'RELEASE_VERSION='$RELEASE_VERSION >> $GITHUB_ENV
          echo 'EXISTING_RELEASE_VERSION='$EXISTING_RELEASE_VERSION >> $GITHUB_ENV

      - name: Generate build
        if: ${{ env.EXISTING_RELEASE_VERSION == '' }}
        run: yarn build

      - name: Create GitHub release
        if: ${{ env.EXISTING_RELEASE_VERSION == '' }}
        uses: ncipollo/release-action@v1
        with:
          name: Fast Scroll v${{ env.RELEASE_VERSION }}
          tag: v${{ env.RELEASE_VERSION }}
          commit: main
          draft: true
          allowUpdates: false
          artifacts: 'build/*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
