name: Release

on:
  push:
    tags: [v*]

env:
  CACHE_VERSION: v1

jobs:
  build-and-release-on-github:
    name: Build and release on GitHub
    runs-on: ubuntu-latest
    environment: GitHub Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ env.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-dependencies-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate build
        run: yarn build

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: Fast Scroll ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/*.zip'
          allowUpdates: false
          draft: true
